In [21]:
# Import the main client and environment variables
from pykalshi import KalshiClient
import os
import pandas as pd
from dotenv import load_dotenv

# (Optional but recommended) Import specific models if you want type hinting later
from pykalshi import MarketStatus, Action, Side

In [5]:
# 1. Load the hidden variables from the .env file into your system environment
load_dotenv(override=True)

# 2. Initialize the client. 
# PyKalshi is smart enough to automatically look for KALSHI_API_KEY_ID 
# and KALSHI_PRIVATE_KEY_PATH in your environment variables.
try:
    client = KalshiClient()
    balance = client.portfolio.get_balance()
    print(f"Connection Successful! Balance: ${balance.balance / 100:.2f}")
except Exception as e:
    # If the library uses a different variable name for the environment, we will catch it here
    print(f"Connection failed: {e}")

Connection Successful! Balance: $68.31

In [7]:
pd.set_option('display.max_columns', None)

In [118]:

#response = client.get_markets(
#    series_ticker='KXHIGHLAX',  
#    fetch_all=True
#)

# Convert the massive response instantly to a DataFrame
#df_summary_LA = response.to_dataframe()
#df_summary_LA = df_summary_LA[['ticker','open_time','close_time','yes_sub_title','status', 'result', 'settlement_value', 'yes_bid', 'yes_ask', 'no_bid', 'no_ask', 'last_price',
#                                   'previous_yes_bid', 'previous_yes_ask', 'previous_price', 'notional_value', 'volume', 'volume_24h', 'open_interest',
#                                   'liquidity', 'tick_size', 'strike_type']]

#df_summary_LA = df_summary_LA[df_summary_LA['volume'] > 1000]
#df_summary_LA.shape
#df_summary_LA.to_csv("filtered_LA_weather_kalshi_market.csv", index=False)

#print("Data successfully saved to filtered_kalshi_markets.csv!")

In [ ]:
#tickers = summary_df['ticker'].tolist()
#all_trades = []
#print(f"Starting deep dive on {len(tickers)} markets...")

#for ticker in tickers:
 #   print(f"Fetching tick data for: {ticker}")
    
   # try:
        # Use the magic flag you found in the pykalshi source code!
   #     response = client.get_trades(
   #         ticker=ticker,
  #          fetch_all=True
  #      )
        
        # Instantly convert the raw trades to a DataFrame
  #      df_trades = response.to_dataframe()
        
        # CRITICAL: We must stamp the ticker name onto these rows, 
        # otherwise we won't know which market the trades belong to later!
#        df_trades['ticker'] = ticker
        
        # Add this market's data to our master list
 #       all_trades.append(df_trades)
        
#    except Exception as e:
 #       print(f"Error fetching {ticker}: {e}")
        
    # Always pause for half a second between API calls so Kalshi doesn't ban your IP
#    time.sleep(0.5)
#print("Stitching dataframes together...")
#master_trades_df = pd.concat(all_trades, ignore_index=True)
#master_trades_df.to_csv("all_LA_weather_trade_data_3-2-26.csv", index = False)

Starting deep dive on 2238 markets...
Fetching tick data for: KXHIGHLAX-26MAR03-T67
Fetching tick data for: KXHIGHLAX-26MAR03-B73.5
Fetching tick data for: KXHIGHLAX-26MAR03-B71.5
Fetching tick data for: KXHIGHLAX-26MAR03-B67.5
Fetching tick data for: KXHIGHLAX-26MAR02-T73
Fetching tick data for: KXHIGHLAX-26MAR02-T66
Fetching tick data for: KXHIGHLAX-26MAR02-B72.5
Fetching tick data for: KXHIGHLAX-26MAR02-B70.5
Fetching tick data for: KXHIGHLAX-26MAR02-B68.5
Fetching tick data for: KXHIGHLAX-26MAR02-B66.5
Fetching tick data for: KXHIGHLAX-26MAR01-T78
Fetching tick data for: KXHIGHLAX-26MAR01-T71
Fetching tick data for: KXHIGHLAX-26MAR01-B77.5
Fetching tick data for: KXHIGHLAX-26MAR01-B75.5
Fetching tick data for: KXHIGHLAX-26MAR01-B73.5
Fetching tick data for: KXHIGHLAX-26MAR01-B71.5
Fetching tick data for: KXHIGHLAX-26FEB28-T80
Fetching tick data for: KXHIGHLAX-26FEB28-T73
Fetching tick data for: KXHIGHLAX-26FEB28-B79.5
Fetching tick data for: KXHIGHLAX-26FEB28-B77.5
Fetching tick data for: KXHIGHLAX-26FEB28-B75.5
Fetching tick data for: KXHIGHLAX-26FEB28-B73.5
Fetching tick data for: KXHIGHLAX-26FEB27-T83
Fetching tick data for: KXHIGHLAX-26FEB27-T76
Fetching tick data for: KXHIGHLAX-26FEB27-B82.5
Fetching tick data for: KXHIGHLAX-26FEB27-B80.5
Fetching tick data for: KXHIGHLAX-26FEB27-B78.5
Fetching tick data for: KXHIGHLAX-26FEB27-B76.5
Fetching tick data for: KXHIGHLAX-26FEB26-T83
Fetching tick data for: KXHIGHLAX-26FEB26-T76
Fetching tick data for: KXHIGHLAX-26FEB26-B82.5
Fetching tick data for: KXHIGHLAX-26FEB26-B80.5
Fetching tick data for: KXHIGHLAX-26FEB26-B78.5
Fetching tick data for: KXHIGHLAX-26FEB26-B76.5
Fetching tick data for: KXHIGHLAX-26FEB25-T80
Fetching tick data for: KXHIGHLAX-26FEB25-T73
Fetching tick data for: KXHIGHLAX-26FEB25-B79.5
Fetching tick data for: KXHIGHLAX-26FEB25-B77.5
Fetching tick data for: KXHIGHLAX-26FEB25-B75.5
Fetching tick data for: KXHIGHLAX-26FEB25-B73.5
Fetching tick data for: KXHIGHLAX-26FEB24-T76
Fetching tick data for: KXHIGHLAX-26FEB24-T69
Fetching tick data for: KXHIGHLAX-26FEB24-B75.5
Fetching tick data for: KXHIGHLAX-26FEB24-B73.5
Fetching tick data for: KXHIGHLAX-26FEB24-B71.5
Fetching tick data for: KXHIGHLAX-26FEB24-B69.5
Fetching tick data for: KXHIGHLAX-26FEB23-T78
Fetching tick data for: KXHIGHLAX-26FEB23-T71
Fetching tick data for: KXHIGHLAX-26FEB23-B77.5
Fetching tick data for: KXHIGHLAX-26FEB23-B75.5
Fetching tick data for: KXHIGHLAX-26FEB23-B73.5
Fetching tick data for: KXHIGHLAX-26FEB23-B71.5
Fetching tick data for: KXHIGHLAX-26FEB22-T74
Fetching tick data for: KXHIGHLAX-26FEB22-T67
Fetching tick data for: KXHIGHLAX-26FEB22-B73.5
Fetching tick data for: KXHIGHLAX-26FEB22-B71.5
Fetching tick data for: KXHIGHLAX-26FEB22-B69.5
Fetching tick data for: KXHIGHLAX-26FEB22-B67.5
Fetching tick data for: KXHIGHLAX-26FEB21-T73
Fetching tick data for: KXHIGHLAX-26FEB21-T66
Fetching tick data for: KXHIGHLAX-26FEB21-B72.5
Fetching tick data for: KXHIGHLAX-26FEB21-B70.5
Fetching tick data for: KXHIGHLAX-26FEB21-B68.5
Fetching tick data for: KXHIGHLAX-26FEB21-B66.5
Fetching tick data for: KXHIGHLAX-26FEB20-T63
Fetching tick data for: KXHIGHLAX-26FEB20-T56
Fetching tick data for: KXHIGHLAX-26FEB20-B62.5
Fetching tick data for: KXHIGHLAX-26FEB20-B60.5
Fetching tick data for: KXHIGHLAX-26FEB20-B58.5
Fetching tick data for: KXHIGHLAX-26FEB20-B56.5
Fetching tick data for: KXHIGHLAX-26FEB19-T64
Fetching tick data for: KXHIGHLAX-26FEB19-T57
Fetching tick data for: KXHIGHLAX-26FEB19-B63.5
Fetching tick data for: KXHIGHLAX-26FEB19-B61.5
Fetching tick data for: KXHIGHLAX-26FEB19-B59.5
Fetching tick data for: KXHIGHLAX-26FEB19-B57.5
Fetching tick data for: KXHIGHLAX-26FEB18-T62
Fetching tick data for: KXHIGHLAX-26FEB18-T55
Fetching tick data for: KXHIGHLAX-26FEB18-B61.5
Fetching tick data for: KXHIGHLAX-26FEB18-B59.5
Fetching tick data for: KXHIGHLAX-26FEB18-B57.5
Fetching tick data for: KXHIGHLAX-26FEB18-B55.5
Fetching tick data for: KXHIGHLAX-26FEB17-T66
Fetching tick data for: KXHIGHLAX-26FEB17-T59
Fetching tick data for: KXHIGHLAX-26FEB17-B65.5
Fetching tick data for: KXHIGHLAX-26FEB17-B63.5
Fetching tick data for: KXHIGHLAX-26FEB17-B61.5
Fetching tick data for: KXHIGHLAX-26FEB17-B59.5
Fetching tick data for: KXHIGHLAX-26FEB16-T65
Fetching tick data for: KXHIGHLAX-26FEB16-T58
Fetching tick data for: KXHIGHLAX-26FEB16-B64.5
Fetching tick data for: KXHIGHLAX-26FEB16-B62.5
Fetching tick data for: KXHIGHLAX-26FEB16-B60.5
Fetching tick data for: KXHIGHLAX-26FEB16-B58.5
Fetching tick data for: KXHIGHLAX-26FEB15-T69
Fetching tick data for: KXHIGHLAX-26FEB15-T62
Fetching tick data for: KXHIGHLAX-26FEB15-B68.5
Fetching tick data for: KXHIGHLAX-26FEB15-B66.5
Fetching tick data for: KXHIGHLAX-26FEB15-B64.5
Fetching tick data for: KXHIGHLAX-26FEB15-B62.5
Fetching tick data for: KXHIGHLAX-26FEB14-T69
Fetching tick data for: KXHIGHLAX-26FEB14-T62
Fetching tick data for: KXHIGHLAX-26FEB14-B68.5
Fetching tick data for: KXHIGHLAX-26FEB14-B66.5
Fetching tick data for: KXHIGHLAX-26FEB14-B64.5
Fetching tick data for: KXHIGHLAX-26FEB14-B62.5
Fetching tick data for: KXHIGHLAX-26FEB13-T73
Fetching tick data for: KXHIGHLAX-26FEB13-T66
Fetching tick data for: KXHIGHLAX-26FEB13-B72.5
Fetching tick data for: KXHIGHLAX-26FEB13-B70.5
Fetching tick data for: KXHIGHLAX-26FEB13-B68.5
Fetching tick data for: KXHIGHLAX-26FEB13-B66.5
Fetching tick data for: KXHIGHLAX-26FEB12-T71
Fetching tick data for: KXHIGHLAX-26FEB12-T64
Fetching tick data for: KXHIGHLAX-26FEB12-B70.5
Fetching tick data for: KXHIGHLAX-26FEB12-B68.5
Fetching tick data for: KXHIGHLAX-26FEB12-B66.5
Fetching tick data for: KXHIGHLAX-26FEB12-B64.5
Fetching tick data for: KXHIGHLAX-26FEB11-T69
Fetching tick data for: KXHIGHLAX-26FEB11-T62
Fetching tick data for: KXHIGHLAX-26FEB11-B68.5
Fetching tick data for: KXHIGHLAX-26FEB11-B66.5
Fetching tick data for: KXHIGHLAX-26FEB11-B64.5
Fetching tick data for: KXHIGHLAX-26FEB11-B62.5
Fetching tick data for: KXHIGHLAX-26FEB10-T70
Fetching tick data for: KXHIGHLAX-26FEB10-T63
Fetching tick data for: KXHIGHLAX-26FEB10-B69.5
Fetching tick data for: KXHIGHLAX-26FEB10-B67.5
Fetching tick data for: KXHIGHLAX-26FEB10-B65.5
Fetching tick data for: KXHIGHLAX-26FEB10-B63.5
Fetching tick data for: KXHIGHLAX-26FEB09-T81
Fetching tick data for: KXHIGHLAX-26FEB09-T74
Fetching tick data for: KXHIGHLAX-26FEB09-B80.5
Fetching tick data for: KXHIGHLAX-26FEB09-B78.5
Fetching tick data for: KXHIGHLAX-26FEB09-B76.5
Fetching tick data for: KXHIGHLAX-26FEB09-B74.5
Fetching tick data for: KXHIGHLAX-26FEB08-T82
Fetching tick data for: KXHIGHLAX-26FEB08-T75
Fetching tick data for: KXHIGHLAX-26FEB08-B81.5
Fetching tick data for: KXHIGHLAX-26FEB08-B79.5
Fetching tick data for: KXHIGHLAX-26FEB08-B77.5
Fetching tick data for: KXHIGHLAX-26FEB08-B75.5
Fetching tick data for: KXHIGHLAX-26FEB07-T75
Fetching tick data for: KXHIGHLAX-26FEB07-T68
Fetching tick data for: KXHIGHLAX-26FEB07-B74.5
Fetching tick data for: KXHIGHLAX-26FEB07-B72.5
Fetching tick data for: KXHIGHLAX-26FEB07-B70.5
Fetching tick data for: KXHIGHLAX-26FEB07-B68.5
Fetching tick data for: KXHIGHLAX-26FEB06-T74
Fetching tick data for: KXHIGHLAX-26FEB06-T67
Fetching tick data for: KXHIGHLAX-26FEB06-B73.5
Fetching tick data for: KXHIGHLAX-26FEB06-B71.5
Fetching tick data for: KXHIGHLAX-26FEB06-B69.5
Fetching tick data for: KXHIGHLAX-26FEB06-B67.5
Fetching tick data for: KXHIGHLAX-26FEB05-T84
Fetching tick data for: KXHIGHLAX-26FEB05-T77
Fetching tick data for: KXHIGHLAX-26FEB05-B83.5
Fetching tick data for: KXHIGHLAX-26FEB05-B81.5
Fetching tick data for: KXHIGHLAX-26FEB05-B79.5
Fetching tick data for: KXHIGHLAX-26FEB05-B77.5
Fetching tick data for: KXHIGHLAX-26FEB04-T87
Fetching tick data for: KXHIGHLAX-26FEB04-T80
Fetching tick data for: KXHIGHLAX-26FEB04-B86.5
Fetching tick data for: KXHIGHLAX-26FEB04-B84.5
Fetching tick data for: KXHIGHLAX-26FEB04-B82.5
Fetching tick data for: KXHIGHLAX-26FEB04-B80.5
Fetching tick data for: KXHIGHLAX-26FEB03-T81
Fetching tick data for: KXHIGHLAX-26FEB03-T74
Fetching tick data for: KXHIGHLAX-26FEB03-B80.5
Fetching tick data for: KXHIGHLAX-26FEB03-B78.5
Fetching tick data for: KXHIGHLAX-26FEB03-B76.5
Fetching tick data for: KXHIGHLAX-26FEB03-B74.5
Fetching tick data for: KXHIGHLAX-26FEB02-T76
Fetching tick data for: KXHIGHLAX-26FEB02-T69
Fetching tick data for: KXHIGHLAX-26FEB02-B75.5
Fetching tick data for: KXHIGHLAX-26FEB02-B73.5
Fetching tick data for: KXHIGHLAX-26FEB02-B71.5
Fetching tick data for: KXHIGHLAX-26FEB02-B69.5
Fetching tick data for: KXHIGHLAX-26FEB01-T79
Fetching tick data for: KXHIGHLAX-26FEB01-T72
Fetching tick data for: KXHIGHLAX-26FEB01-B78.5
Fetching tick data for: KXHIGHLAX-26FEB01-B76.5
Fetching tick data for: KXHIGHLAX-26FEB01-B74.5
Fetching tick data for: KXHIGHLAX-26FEB01-B72.5
Fetching tick data for: KXHIGHLAX-26JAN31-T88
Fetching tick data for: KXHIGHLAX-26JAN31-T81
Fetching tick data for: KXHIGHLAX-26JAN31-B87.5
Fetching tick data for: KXHIGHLAX-26JAN31-B85.5
Fetching tick data for: KXHIGHLAX-26JAN31-B83.5
Fetching tick data for: KXHIGHLAX-26JAN31-B81.5
Fetching tick data for: KXHIGHLAX-26JAN30-T86
Fetching tick data for: KXHIGHLAX-26JAN30-T79
Fetching tick data for: KXHIGHLAX-26JAN30-B85.5
Fetching tick data for: KXHIGHLAX-26JAN30-B83.5
Fetching tick data for: KXHIGHLAX-26JAN30-B81.5
Fetching tick data for: KXHIGHLAX-26JAN30-B79.5
Fetching tick data for: KXHIGHLAX-26JAN29-T82
Fetching tick data for: KXHIGHLAX-26JAN29-T75
Fetching tick data for: KXHIGHLAX-26JAN29-B81.5
Fetching tick data for: KXHIGHLAX-26JAN29-B79.5
Fetching tick data for: KXHIGHLAX-26JAN29-B77.5
Fetching tick data for: KXHIGHLAX-26JAN29-B75.5
Fetching tick data for: KXHIGHLAX-26JAN28-T72
Fetching tick data for: KXHIGHLAX-26JAN28-T65
Fetching tick data for: KXHIGHLAX-26JAN28-B71.5
Fetching tick data for: KXHIGHLAX-26JAN28-B69.5
Fetching tick data for: KXHIGHLAX-26JAN28-B67.5
Fetching tick data for: KXHIGHLAX-26JAN28-B65.5
Fetching tick data for: KXHIGHLAX-26JAN27-T75
Fetching tick data for: KXHIGHLAX-26JAN27-T68
Fetching tick data for: KXHIGHLAX-26JAN27-B74.5
Fetching tick data for: KXHIGHLAX-26JAN27-B72.5
Fetching tick data for: KXHIGHLAX-26JAN27-B70.5
Fetching tick data for: KXHIGHLAX-26JAN27-B68.5
Fetching tick data for: KXHIGHLAX-26JAN26-T75
Fetching tick data for: KXHIGHLAX-26JAN26-T68
Fetching tick data for: KXHIGHLAX-26JAN26-B74.5
Fetching tick data for: KXHIGHLAX-26JAN26-B72.5
Fetching tick data for: KXHIGHLAX-26JAN26-B70.5
Fetching tick data for: KXHIGHLAX-26JAN26-B68.5
Fetching tick data for: KXHIGHLAX-26JAN25-T71
Fetching tick data for: KXHIGHLAX-26JAN25-T64
Fetching tick data for: KXHIGHLAX-26JAN25-B70.5
Fetching tick data for: KXHIGHLAX-26JAN25-B68.5
Fetching tick data for: KXHIGHLAX-26JAN25-B66.5
Fetching tick data for: KXHIGHLAX-26JAN25-B64.5
Fetching tick data for: KXHIGHLAX-26JAN24-T66
Fetching tick data for: KXHIGHLAX-26JAN24-T59
Fetching tick data for: KXHIGHLAX-26JAN24-B65.5
Fetching tick data for: KXHIGHLAX-26JAN24-B63.5
Fetching tick data for: KXHIGHLAX-26JAN24-B61.5
Fetching tick data for: KXHIGHLAX-26JAN24-B59.5
Fetching tick data for: KXHIGHLAX-26JAN23-T66
Fetching tick data for: KXHIGHLAX-26JAN23-T59
Fetching tick data for: KXHIGHLAX-26JAN23-B65.5
Fetching tick data for: KXHIGHLAX-26JAN23-B63.5
Fetching tick data for: KXHIGHLAX-26JAN23-B61.5
Fetching tick data for: KXHIGHLAX-26JAN23-B59.5
Fetching tick data for: KXHIGHLAX-26JAN22-T69
Fetching tick data for: KXHIGHLAX-26JAN22-T62
Fetching tick data for: KXHIGHLAX-26JAN22-B68.5
Fetching tick data for: KXHIGHLAX-26JAN22-B66.5
Fetching tick data for: KXHIGHLAX-26JAN22-B64.5
Fetching tick data for: KXHIGHLAX-26JAN22-B62.5
Fetching tick data for: KXHIGHLAX-26JAN21-T71
Fetching tick data for: KXHIGHLAX-26JAN21-T64
Fetching tick data for: KXHIGHLAX-26JAN21-B70.5
Fetching tick data for: KXHIGHLAX-26JAN21-B68.5
Fetching tick data for: KXHIGHLAX-26JAN21-B66.5
Fetching tick data for: KXHIGHLAX-26JAN21-B64.5
Fetching tick data for: KXHIGHLAX-26JAN20-T77
Fetching tick data for: KXHIGHLAX-26JAN20-T70
Fetching tick data for: KXHIGHLAX-26JAN20-B76.5
Fetching tick data for: KXHIGHLAX-26JAN20-B74.5
Fetching tick data for: KXHIGHLAX-26JAN20-B72.5
Fetching tick data for: KXHIGHLAX-26JAN20-B70.5
Fetching tick data for: KXHIGHLAX-26JAN19-T76
Fetching tick data for: KXHIGHLAX-26JAN19-T69
Fetching tick data for: KXHIGHLAX-26JAN19-B75.5
Fetching tick data for: KXHIGHLAX-26JAN19-B73.5
Fetching tick data for: KXHIGHLAX-26JAN19-B71.5
Fetching tick data for: KXHIGHLAX-26JAN19-B69.5
Fetching tick data for: KXHIGHLAX-26JAN18-T76
Fetching tick data for: KXHIGHLAX-26JAN18-T69
Fetching tick data for: KXHIGHLAX-26JAN18-B75.5
Fetching tick data for: KXHIGHLAX-26JAN18-B73.5
Fetching tick data for: KXHIGHLAX-26JAN18-B71.5
Fetching tick data for: KXHIGHLAX-26JAN18-B69.5
Fetching tick data for: KXHIGHLAX-26JAN17-T81
Fetching tick data for: KXHIGHLAX-26JAN17-T74
Fetching tick data for: KXHIGHLAX-26JAN17-B80.5
Fetching tick data for: KXHIGHLAX-26JAN17-B78.5
Fetching tick data for: KXHIGHLAX-26JAN17-B76.5
Fetching tick data for: KXHIGHLAX-26JAN17-B74.5
Fetching tick data for: KXHIGHLAX-26JAN16-T81
Fetching tick data for: KXHIGHLAX-26JAN16-T74
Fetching tick data for: KXHIGHLAX-26JAN16-B80.5
Fetching tick data for: KXHIGHLAX-26JAN16-B78.5
Fetching tick data for: KXHIGHLAX-26JAN16-B76.5
Fetching tick data for: KXHIGHLAX-26JAN16-B74.5
Fetching tick data for: KXHIGHLAX-26JAN15-T82
Fetching tick data for: KXHIGHLAX-26JAN15-T75
Fetching tick data for: KXHIGHLAX-26JAN15-B81.5
Fetching tick data for: KXHIGHLAX-26JAN15-B79.5
Fetching tick data for: KXHIGHLAX-26JAN15-B77.5
Fetching tick data for: KXHIGHLAX-26JAN15-B75.5
Fetching tick data for: KXHIGHLAX-26JAN14-T83
Fetching tick data for: KXHIGHLAX-26JAN14-T76
Fetching tick data for: KXHIGHLAX-26JAN14-B82.5
Fetching tick data for: KXHIGHLAX-26JAN14-B80.5
Fetching tick data for: KXHIGHLAX-26JAN14-B78.5
Fetching tick data for: KXHIGHLAX-26JAN14-B76.5
Fetching tick data for: KXHIGHLAX-26JAN13-T81
Fetching tick data for: KXHIGHLAX-26JAN13-T74
Fetching tick data for: KXHIGHLAX-26JAN13-B80.5
Fetching tick data for: KXHIGHLAX-26JAN13-B78.5
Fetching tick data for: KXHIGHLAX-26JAN13-B76.5
Fetching tick data for: KXHIGHLAX-26JAN13-B74.5
Fetching tick data for: KXHIGHLAX-26JAN12-T77
Fetching tick data for: KXHIGHLAX-26JAN12-T70
Fetching tick data for: KXHIGHLAX-26JAN12-B76.5
Fetching tick data for: KXHIGHLAX-26JAN12-B74.5
Fetching tick data for: KXHIGHLAX-26JAN12-B72.5
Fetching tick data for: KXHIGHLAX-26JAN12-B70.5
Fetching tick data for: KXHIGHLAX-26JAN11-T73
Fetching tick data for: KXHIGHLAX-26JAN11-T66
Fetching tick data for: KXHIGHLAX-26JAN11-B72.5
Fetching tick data for: KXHIGHLAX-26JAN11-B70.5
Fetching tick data for: KXHIGHLAX-26JAN11-B68.5
Fetching tick data for: KXHIGHLAX-26JAN11-B66.5
Fetching tick data for: KXHIGHLAX-26JAN10-T71
Fetching tick data for: KXHIGHLAX-26JAN10-T64
Fetching tick data for: KXHIGHLAX-26JAN10-B70.5
Fetching tick data for: KXHIGHLAX-26JAN10-B68.5
Fetching tick data for: KXHIGHLAX-26JAN10-B66.5
Fetching tick data for: KXHIGHLAX-26JAN10-B64.5
Fetching tick data for: KXHIGHLAX-26JAN09-T67
Fetching tick data for: KXHIGHLAX-26JAN09-T60
Fetching tick data for: KXHIGHLAX-26JAN09-B66.5
Fetching tick data for: KXHIGHLAX-26JAN09-B64.5
Fetching tick data for: KXHIGHLAX-26JAN09-B62.5
Fetching tick data for: KXHIGHLAX-26JAN09-B60.5
Fetching tick data for: KXHIGHLAX-26JAN08-T66
Fetching tick data for: KXHIGHLAX-26JAN08-T59
Fetching tick data for: KXHIGHLAX-26JAN08-B65.5
Fetching tick data for: KXHIGHLAX-26JAN08-B63.5
Fetching tick data for: KXHIGHLAX-26JAN08-B61.5
Fetching tick data for: KXHIGHLAX-26JAN08-B59.5
Fetching tick data for: KXHIGHLAX-26JAN07-T68
Fetching tick data for: KXHIGHLAX-26JAN07-T61
Fetching tick data for: KXHIGHLAX-26JAN07-B67.5
Fetching tick data for: KXHIGHLAX-26JAN07-B65.5
Fetching tick data for: KXHIGHLAX-26JAN07-B63.5
Fetching tick data for: KXHIGHLAX-26JAN07-B61.5
Fetching tick data for: KXHIGHLAX-26JAN06-T69
Fetching tick data for: KXHIGHLAX-26JAN06-T62
Fetching tick data for: KXHIGHLAX-26JAN06-B68.5
Fetching tick data for: KXHIGHLAX-26JAN06-B66.5
Fetching tick data for: KXHIGHLAX-26JAN06-B64.5
Fetching tick data for: KXHIGHLAX-26JAN06-B62.5
Fetching tick data for: KXHIGHLAX-26JAN05-T66
Fetching tick data for: KXHIGHLAX-26JAN05-T59
Fetching tick data for: KXHIGHLAX-26JAN05-B65.5
Fetching tick data for: KXHIGHLAX-26JAN05-B63.5
Fetching tick data for: KXHIGHLAX-26JAN05-B61.5
Fetching tick data for: KXHIGHLAX-26JAN05-B59.5
Fetching tick data for: KXHIGHLAX-26JAN04-T67
Fetching tick data for: KXHIGHLAX-26JAN04-T60
Fetching tick data for: KXHIGHLAX-26JAN04-B66.5
Fetching tick data for: KXHIGHLAX-26JAN04-B64.5
Fetching tick data for: KXHIGHLAX-26JAN04-B62.5
Fetching tick data for: KXHIGHLAX-26JAN04-B60.5
Fetching tick data for: KXHIGHLAX-26JAN03-T68
Fetching tick data for: KXHIGHLAX-26JAN03-T61
Fetching tick data for: KXHIGHLAX-26JAN03-B67.5
Fetching tick data for: KXHIGHLAX-26JAN03-B65.5
Fetching tick data for: KXHIGHLAX-26JAN03-B63.5
Fetching tick data for: KXHIGHLAX-26JAN03-B61.5
Fetching tick data for: KXHIGHLAX-26JAN02-T69
Fetching tick data for: KXHIGHLAX-26JAN02-T62
Fetching tick data for: KXHIGHLAX-26JAN02-B68.5
Fetching tick data for: KXHIGHLAX-26JAN02-B66.5
Fetching tick data for: KXHIGHLAX-26JAN02-B64.5
Fetching tick data for: KXHIGHLAX-26JAN02-B62.5
Fetching tick data for: KXHIGHLAX-26JAN01-T68
Fetching tick data for: KXHIGHLAX-26JAN01-T61
Fetching tick data for: KXHIGHLAX-26JAN01-B67.5
Fetching tick data for: KXHIGHLAX-26JAN01-B65.5
Fetching tick data for: KXHIGHLAX-26JAN01-B63.5
Fetching tick data for: KXHIGHLAX-26JAN01-B61.5
Fetching tick data for: KXHIGHLAX-25DEC31-T70
Fetching tick data for: KXHIGHLAX-25DEC31-T63
Fetching tick data for: KXHIGHLAX-25DEC31-B69.5
Fetching tick data for: KXHIGHLAX-25DEC31-B67.5
Fetching tick data for: KXHIGHLAX-25DEC31-B65.5
Fetching tick data for: KXHIGHLAX-25DEC31-B63.5
Fetching tick data for: KXHIGHLAX-25DEC30-T75
Fetching tick data for: KXHIGHLAX-25DEC30-T68
Fetching tick data for: KXHIGHLAX-25DEC30-B74.5
Fetching tick data for: KXHIGHLAX-25DEC30-B72.5
Fetching tick data for: KXHIGHLAX-25DEC30-B70.5
Fetching tick data for: KXHIGHLAX-25DEC30-B68.5
Fetching tick data for: KXHIGHLAX-25DEC29-T73
Fetching tick data for: KXHIGHLAX-25DEC29-T66
Fetching tick data for: KXHIGHLAX-25DEC29-B72.5
Fetching tick data for: KXHIGHLAX-25DEC29-B70.5
Fetching tick data for: KXHIGHLAX-25DEC29-B68.5
Fetching tick data for: KXHIGHLAX-25DEC29-B66.5
Fetching tick data for: KXHIGHLAX-25DEC28-T67
Fetching tick data for: KXHIGHLAX-25DEC28-T60
Fetching tick data for: KXHIGHLAX-25DEC28-B66.5
Fetching tick data for: KXHIGHLAX-25DEC28-B64.5
Fetching tick data for: KXHIGHLAX-25DEC28-B62.5
Fetching tick data for: KXHIGHLAX-25DEC28-B60.5
Fetching tick data for: KXHIGHLAX-25DEC27-T63
Fetching tick data for: KXHIGHLAX-25DEC27-T56
Fetching tick data for: KXHIGHLAX-25DEC27-B62.5
Fetching tick data for: KXHIGHLAX-25DEC27-B60.5
Fetching tick data for: KXHIGHLAX-25DEC27-B58.5
Fetching tick data for: KXHIGHLAX-25DEC27-B56.5
Fetching tick data for: KXHIGHLAX-25DEC26-T65
Fetching tick data for: KXHIGHLAX-25DEC26-T58
Fetching tick data for: KXHIGHLAX-25DEC26-B64.5
Fetching tick data for: KXHIGHLAX-25DEC26-B62.5
Fetching tick data for: KXHIGHLAX-25DEC26-B60.5
Fetching tick data for: KXHIGHLAX-25DEC26-B58.5
Fetching tick data for: KXHIGHLAX-25DEC25-T67
Fetching tick data for: KXHIGHLAX-25DEC25-T60
Fetching tick data for: KXHIGHLAX-25DEC25-B66.5
Fetching tick data for: KXHIGHLAX-25DEC25-B64.5
Fetching tick data for: KXHIGHLAX-25DEC25-B62.5
Fetching tick data for: KXHIGHLAX-25DEC25-B60.5
Fetching tick data for: KXHIGHLAX-25DEC24-T69
Fetching tick data for: KXHIGHLAX-25DEC24-T62
Fetching tick data for: KXHIGHLAX-25DEC24-B68.5
Fetching tick data for: KXHIGHLAX-25DEC24-B66.5
Fetching tick data for: KXHIGHLAX-25DEC24-B64.5
Fetching tick data for: KXHIGHLAX-25DEC24-B62.5
Fetching tick data for: KXHIGHLAX-25DEC23-T67
Fetching tick data for: KXHIGHLAX-25DEC23-T60
Fetching tick data for: KXHIGHLAX-25DEC23-B66.5

In [9]:
summary_df = pd.read_csv("filtered_LA_weather_kalshi_market_3-2-2026.csv")

In [15]:
summary_df.tail()

,ticker,open_time,close_time,yes_sub_title,status,result,settlement_value,yes_bid,yes_ask,no_bid,...,previous_yes_bid,previous_yes_ask,previous_price,notional_value,volume,volume_24h,open_interest,liquidity,tick_size,strike_type
2233,KXHIGHLAX-25JAN05-T73,2025-01-04T20:00:00Z,2025-01-06T07:59:00Z,74° or above,finalized,yes,100.0,99,100,0,...,99,100,99,100,13599,0,6270,0,1,greater
2234,KXHIGHLAX-25JAN05-B72.5,2025-01-04T20:00:00Z,2025-01-06T07:59:00Z,72° to 73°,finalized,no,0.0,0,1,99,...,0,1,1,100,10019,0,6605,0,1,between
2235,KXHIGHLAX-25JAN05-B70.5,2025-01-04T20:00:00Z,2025-01-06T07:59:00Z,70° to 71°,finalized,no,0.0,0,1,99,...,0,1,1,100,7125,0,4352,0,1,between
2236,KXHIGHLAX-25JAN05-B68.5,2025-01-04T20:00:00Z,2025-01-06T07:59:00Z,68° to 69°,finalized,no,0.0,0,1,99,...,0,1,1,100,3179,0,1650,0,1,between
2237,KXHIGHLAX-25JAN05-T66,2025-01-04T20:00:00Z,2025-01-06T07:59:00Z,65° or below,finalized,no,0.0,0,1,99,...,0,1,1,100,1228,0,672,0,1,less

In [89]:
summary_df['close_time'] = pd.to_datetime(summary_df['close_time'], utc=True)

# 2. Shift it to our strict Pacific Standard Time (-08:00)
summary_df['close_time'] = summary_df['close_time'].dt.tz_convert('-08:00')

# 3. Extract just the local date! 
summary_df['local_date'] = summary_df['close_time'].dt.date

# Check our work to make sure the local_date matches the date in the ticker!
print(summary_df[['ticker', 'close_time', 'local_date', 'result']].head())

                    ticker                close_time  local_date result
0    KXHIGHLAX-26MAR03-T67 2026-03-03 23:59:00-08:00  2026-03-03    NaN
1  KXHIGHLAX-26MAR03-B73.5 2026-03-03 23:59:00-08:00  2026-03-03    NaN
2  KXHIGHLAX-26MAR03-B71.5 2026-03-03 23:59:00-08:00  2026-03-03    NaN
3  KXHIGHLAX-26MAR03-B67.5 2026-03-03 23:59:00-08:00  2026-03-03    NaN
4    KXHIGHLAX-26MAR02-T73 2026-03-02 23:59:00-08:00  2026-03-02    NaN

In [11]:
master_trades_df = pd.read_csv("all_LA_weather_trade_data_3-2-26.csv")

In [13]:
master_trades_df.tail()

,trade_id,ticker,count,yes_price,no_price,taker_side,created_time,ts
1284773,ac6a031f-2b83-4733-8c7b-b18396831562,KXHIGHLAX-25JAN05-T66,7,3,97,no,2025-01-05T03:08:47.757423Z,NaN
1284774,670f3318-e650-47ba-8d87-a0c9f333b977,KXHIGHLAX-25JAN05-T66,5,4,96,no,2025-01-05T03:07:59.363782Z,NaN
1284775,fce1bbef-ff00-4f23-a723-c47e4b4c567b,KXHIGHLAX-25JAN05-T66,1,3,97,no,2025-01-05T01:53:38.924647Z,NaN
1284776,4533ecdf-4f79-41ac-a379-7feac56d7814,KXHIGHLAX-25JAN05-T66,3,2,98,no,2025-01-05T00:08:34.171577Z,NaN
1284777,75a31682-9429-4592-a1c7-aa055ea82f9c,KXHIGHLAX-25JAN05-T66,2,1,99,no,2025-01-04T22:16:08.670572Z,NaN

In [83]:
print("Converting trade timestamps and extracting keys...")

# 1. Convert the raw strings into Pandas datetime objects, forcing them to be recognized as UTC
master_trades_df['created_time'] = pd.to_datetime(master_trades_df['created_time'], utc=True)

# 2. Convert from UTC to our strict NWS timezone (-08:00)
master_trades_df['created_time'] = master_trades_df['created_time'].dt.tz_convert('-08:00')

# 3. Extract the 'local_date' and 'hour' keys
# .dt.date drops the time completely, .dt.hour extracts just the 0-23 hour integer
master_trades_df['local_date'] = master_trades_df['created_time'].dt.date
master_trades_df['hour'] = master_trades_df['created_time'].dt.hour

# Let's check our work!
print(master_trades_df[['created_time', 'local_date', 'hour', 'yes_price']].head())

Converting trade timestamps and extracting keys...
                      created_time  local_date  hour  yes_price
0 2026-03-02 16:32:03.275313-08:00  2026-03-02    16         11
1 2026-03-02 16:31:08.039151-08:00  2026-03-02    16         12
2 2026-03-02 16:29:31.929729-08:00  2026-03-02    16         11
3 2026-03-02 16:29:31.929729-08:00  2026-03-02    16         12
4 2026-03-02 16:16:03.551677-08:00  2026-03-02    16          8

In [85]:
# Squash the individual ticks into hourly chunks
df_hourly_trades = master_trades_df.groupby(['ticker', 'local_date', 'hour']).agg(
    hourly_avg_yes_price=('yes_price', 'mean'),
    hourly_avg_no_price=('no_price', 'mean'),
    hourly_volume=('count', 'sum')
).reset_index()

print("Trade data successfully squashed into hourly rows!")
print(df_hourly_trades.head())

Trade data successfully squashed into hourly rows!
                    ticker  local_date  hour  hourly_avg_yes_price  \
0  KXHIGHLAX-25APR01-B60.5  2025-03-31     7                 12.00
1  KXHIGHLAX-25APR01-B60.5  2025-03-31    18                 10.00
2  KXHIGHLAX-25APR01-B60.5  2025-03-31    19                 14.00
3  KXHIGHLAX-25APR01-B60.5  2025-03-31    20                 15.00
4  KXHIGHLAX-25APR01-B60.5  2025-04-01     4                 16.68

   hourly_avg_no_price  hourly_volume
0                88.00             19
1                90.00             99
2                86.00             13
3                85.00             13
4                83.32           1162

In [3]:
from datetime import datetime
import meteostat as ms

lax = ms.Point(33.9416, -118.4085)
START = datetime(2025, 1, 4)
END = datetime(2026,3,3)
stations = ms.stations.nearby(lax,limit=1)
daily_data = ms.daily(stations,START,END)
df_daily_weather = daily_data.fetch()

In [5]:
df_daily_weather['temp'] = (df_daily_weather['temp'] * 9/5) + 32
df_daily_weather['tmin'] = (df_daily_weather['tmin'] * 9/5) + 32
df_daily_weather['tmax'] = (df_daily_weather['tmax'] * 9/5) + 32
df_daily_weather

                     temp   tmin   tmax  rhum  prcp  snwd  wspd  wpgt    pres  \
station time
72295   2025-01-04  55.22  48.02  62.06    74   0.0  <NA>   7.9  <NA>  1019.0
        2025-01-05  57.74  44.96  75.02    52   0.0  <NA>   6.5  <NA>  1019.5
        2025-01-06  59.18  46.94  71.06    54   0.0  <NA>   4.7  <NA>  1017.2
        2025-01-07  59.54  48.92  73.04    54   0.0  <NA>  21.6  <NA>  1014.5
        2025-01-08  65.12  53.06  73.04    28   0.0  <NA>  16.9  <NA>  1018.6
...                   ...    ...    ...   ...   ...   ...   ...   ...     ...
        2026-02-27  67.64  58.64   77.0    62  <NA>  <NA>   8.6  <NA>  1014.2
        2026-02-28  66.02  59.54  73.58  <NA>  <NA>  <NA>   9.5  <NA>  1013.6
        2026-03-01  62.78  58.64   71.6  <NA>  <NA>  <NA>  11.3  <NA>  1015.1
        2026-03-02   60.8   55.4  66.74  <NA>  <NA>  <NA>  11.8  <NA>  1015.3
        2026-03-03  60.98  53.96  68.36  <NA>  <NA>  <NA>   9.4  <NA>  1016.1

                    tsun  cldc
station time
72295   2025-01-04  <NA>     5
        2025-01-05  <NA>     2
        2025-01-06  <NA>     3
        2025-01-07  <NA>     4
        2025-01-08  <NA>     4
...                  ...   ...
        2026-02-27  <NA>     4
        2026-02-28  <NA>     5
        2026-03-01  <NA>     5
        2026-03-02  <NA>     4
        2026-03-03  <NA>     4

[424 rows x 11 columns]

In [7]:
hourly_data = ms.hourly(stations,START,END)
df_hourly_weather = hourly_data.fetch()
df_hourly_weather['temp'] = (df_hourly_weather['temp'] * 9/5) + 32
df_hourly_weather

                              temp  rhum  prcp  snwd  wdir  wspd  wpgt  \
station time
72295   2025-01-04 00:00:00   59.0    75   0.0  <NA>     0   0.0  <NA>
        2025-01-04 01:00:00  55.94    84   0.0  <NA>   270  24.1  <NA>
        2025-01-04 02:00:00  55.04    86   0.0  <NA>   270  18.4  <NA>
        2025-01-04 03:00:00  55.04    86   0.0  <NA>   270  14.8  <NA>
        2025-01-04 04:00:00  55.04    86   0.0  <NA>   250  11.2  <NA>
...                            ...   ...   ...   ...   ...   ...   ...
        2026-03-02 20:00:00  65.66    67  <NA>  <NA>   252  16.7  <NA>
        2026-03-02 21:00:00   66.2    63  <NA>  <NA>   253  18.5  <NA>
        2026-03-02 22:00:00  64.76    64  <NA>  <NA>   254  20.4  <NA>
        2026-03-02 23:00:00  64.04    63  <NA>  <NA>   253  20.4  <NA>
        2026-03-03 00:00:00  63.86    67  <NA>  <NA>   255  22.2  <NA>

                               pres  tsun  cldc  coco
station time
72295   2025-01-04 00:00:00  1016.4  <NA>     2     3
        2025-01-04 01:00:00  1017.3  <NA>     2     3
        2025-01-04 02:00:00  1017.7  <NA>     2     2
        2025-01-04 03:00:00  1018.0  <NA>     4     2
        2025-01-04 04:00:00  1018.1  <NA>     4     2
...                             ...   ...   ...   ...
        2026-03-02 20:00:00  1015.6  <NA>     4     2
        2026-03-02 21:00:00  1015.1  <NA>     3     2
        2026-03-02 22:00:00  1014.5  <NA>     3     2
        2026-03-02 23:00:00  1013.8  <NA>     2     2
        2026-03-03 00:00:00  1013.7  <NA>     3     2

[10153 rows x 11 columns]

In [9]:
df_hourly_clean = df_hourly_weather.reset_index()

# 2. Tell Pandas the time is UTC, then convert it to strict PST (UTC-8)
# We use -08:00 instead of 'America/Los_Angeles' so Daylight Saving doesn't mess it up
df_hourly_clean['time'] = df_hourly_clean['time'].dt.tz_localize('UTC').dt.tz_convert('-08:00')

# 3. Set the corrected time back as the index so Pandas can do the math
df_hourly_clean = df_hourly_clean.set_index('time')

In [11]:
print(df_hourly_clean.head())

                          station   temp  rhum  prcp  snwd  wdir  wspd  wpgt  \
time
2025-01-03 16:00:00-08:00   72295   59.0    75   0.0  <NA>     0   0.0  <NA>
2025-01-03 17:00:00-08:00   72295  55.94    84   0.0  <NA>   270  24.1  <NA>
2025-01-03 18:00:00-08:00   72295  55.04    86   0.0  <NA>   270  18.4  <NA>
2025-01-03 19:00:00-08:00   72295  55.04    86   0.0  <NA>   270  14.8  <NA>
2025-01-03 20:00:00-08:00   72295  55.04    86   0.0  <NA>   250  11.2  <NA>

                             pres  tsun  cldc  coco
time
2025-01-03 16:00:00-08:00  1016.4  <NA>     2     3
2025-01-03 17:00:00-08:00  1017.3  <NA>     2     3
2025-01-03 18:00:00-08:00  1017.7  <NA>     2     2
2025-01-03 19:00:00-08:00  1018.0  <NA>     4     2
2025-01-03 20:00:00-08:00  1018.1  <NA>     4     2

In [13]:
df_weather = df_hourly_clean[["temp","rhum","wdir","wspd","pres","cldc","coco"]].copy()

In [15]:
import numpy as np

print("Transforming wind direction into cyclical ML features...")

# 1. Trigonometry requires radians, not degrees. 
# We convert the wdir column to radians first.
df_weather['wdir_rad'] = np.deg2rad(df_weather['wdir'])

# 2. Calculate the Sine and Cosine features
df_weather['wdir_sin'] = np.sin(df_weather['wdir_rad'])
df_weather['wdir_cos'] = np.cos(df_weather['wdir_rad'])

# 3. Drop the raw degrees and the intermediate radian column.
# If you leave the raw 'wdir' column in, the model will still try to use it and get confused!
df_weather = df_weather.drop(columns=['wdir', 'wdir_rad'])

# Check your new, machine-learning-ready features!

Transforming wind direction into cyclical ML features...

In [17]:
print(df_weather.head())

                            temp  rhum  wspd    pres  cldc  coco  wdir_sin  \
time
2025-01-03 16:00:00-08:00   59.0    75   0.0  1016.4     2     3       0.0
2025-01-03 17:00:00-08:00  55.94    84  24.1  1017.3     2     3      -1.0
2025-01-03 18:00:00-08:00  55.04    86  18.4  1017.7     2     2      -1.0
2025-01-03 19:00:00-08:00  55.04    86  14.8  1018.0     4     2      -1.0
2025-01-03 20:00:00-08:00  55.04    86  11.2  1018.1     4     2 -0.939693

                           wdir_cos
time
2025-01-03 16:00:00-08:00       1.0
2025-01-03 17:00:00-08:00       0.0
2025-01-03 18:00:00-08:00       0.0
2025-01-03 19:00:00-08:00       0.0
2025-01-03 20:00:00-08:00  -0.34202

In [23]:
df_weather = pd.get_dummies(df_weather, columns=['coco'], prefix='condition', dtype=int)

# Let's see your final, locked-and-loaded ML feature matrix!
print(df_weather.head())

                            temp  rhum  wspd    pres  cldc  wdir_sin  \
time
2025-01-03 16:00:00-08:00   59.0    75   0.0  1016.4     2       0.0
2025-01-03 17:00:00-08:00  55.94    84  24.1  1017.3     2      -1.0
2025-01-03 18:00:00-08:00  55.04    86  18.4  1017.7     2      -1.0
2025-01-03 19:00:00-08:00  55.04    86  14.8  1018.0     4      -1.0
2025-01-03 20:00:00-08:00  55.04    86  11.2  1018.1     4 -0.939693

                           wdir_cos  condition_1  condition_2  condition_3  \
time
2025-01-03 16:00:00-08:00       1.0            0            0            1
2025-01-03 17:00:00-08:00       0.0            0            0            1
2025-01-03 18:00:00-08:00       0.0            0            1            0
2025-01-03 19:00:00-08:00       0.0            0            1            0
2025-01-03 20:00:00-08:00  -0.34202            0            1            0

                           condition_4  condition_5  condition_7  condition_8  \
time
2025-01-03 16:00:00-08:00            0            0            0            0
2025-01-03 17:00:00-08:00            0            0            0            0
2025-01-03 18:00:00-08:00            0            0            0            0
2025-01-03 19:00:00-08:00            0            0            0            0
2025-01-03 20:00:00-08:00            0            0            0            0

                           condition_9  condition_18  condition_25
time
2025-01-03 16:00:00-08:00            0             0             0
2025-01-03 17:00:00-08:00            0             0             0
2025-01-03 18:00:00-08:00            0             0             0
2025-01-03 19:00:00-08:00            0             0             0
2025-01-03 20:00:00-08:00            0             0             0

In [25]:
df_weather = df_weather.reset_index()

# 2. Extract the matching keys using the .dt accessor
df_weather['local_date'] = df_weather['time'].dt.date
df_weather['hour'] = df_weather['time'].dt.hour

# Let's verify the keys are there alongside your engineered features!
print(df_weather[['time', 'local_date', 'hour', 'temp', 'wdir_sin']].head())

                       time  local_date  hour   temp  wdir_sin
0 2025-01-03 16:00:00-08:00  2025-01-03    16   59.0       0.0
1 2025-01-03 17:00:00-08:00  2025-01-03    17  55.94      -1.0
2 2025-01-03 18:00:00-08:00  2025-01-03    18  55.04      -1.0
3 2025-01-03 19:00:00-08:00  2025-01-03    19  55.04      -1.0
4 2025-01-03 20:00:00-08:00  2025-01-03    20  55.04 -0.939693

In [27]:
df_weather.to_csv("weather_only.csv", index = False)

In [95]:
df_master_hourly = pd.merge(
    df_hourly_trades,
    df_weather,
    on=['local_date', 'hour'],
    how='inner'
)

# 2. Second Merge: Broadcast the Daily Summary outcome to every single hour
# We only bring over the specific columns we need from df_summary to avoid clutter
df_golden = pd.merge(
    df_master_hourly,
    summary_df[['ticker', 'local_date', 'result']], 
    on=['ticker', 'local_date'],
    how='inner'
)

# 3. Clean up the Target Variable for Machine Learning
# Scikit-Learn cannot read the words "yes" or "no". It needs math.
df_golden['target_win'] = df_golden['result'].map({'yes': 1, 'no': 0})

# 4. Optional: Drop the original text 'result' column now that we have our binary target
df_golden = df_golden.drop(columns=['result'])

# Save it to your hard drive so you never have to run this massive pipeline again!
df_golden.to_csv("kalshi_weather_matrix.csv", index=False)

print(f"Success! The Golden Matrix has {len(df_golden)} rows.")
print(df_golden.head())

Success! The Golden Matrix has 32359 rows.
                    ticker  local_date  hour  hourly_avg_yes_price  \
0  KXHIGHLAX-25APR01-B60.5  2025-04-01     4             16.680000
1  KXHIGHLAX-25APR01-B60.5  2025-04-01     5             15.733333
2  KXHIGHLAX-25APR01-B60.5  2025-04-01     6             13.333333
3  KXHIGHLAX-25APR01-B60.5  2025-04-01     7             10.900000
4  KXHIGHLAX-25APR01-B60.5  2025-04-01     8              7.222222

   hourly_avg_no_price  hourly_volume                      time   temp  rhum  \
0            83.320000           1162 2025-04-01 04:00:00-08:00  53.96    83
1            84.266667            190 2025-04-01 05:00:00-08:00  53.96    72
2            86.666667            140 2025-04-01 06:00:00-08:00  53.06    74
3            89.100000             47 2025-04-01 07:00:00-08:00  55.04    72
4            92.777778            292 2025-04-01 08:00:00-08:00  57.02    64

   wspd    pres  cldc  wdir_sin  wdir_cos  condition_1  condition_2  \
0  18.4  1014.9     4      -1.0       0.0            0            1
1   7.6  1015.0     4 -0.766045  0.642788            0            0
2  11.2  1015.3     6 -0.866025       0.5            0            0
3  16.6  1015.8     6 -0.984808  0.173648            0            0
4  18.4  1015.9     4 -0.984808  0.173648            0            0

   condition_3  condition_4  condition_5  condition_7  condition_8  \
0            0            0            0            0            0
1            1            0            0            0            0
2            1            0            0            0            0
3            1            0            0            0            0
4            1            0            0            0            0

   condition_9  condition_18  condition_25  target_win
0            0             0             0         0.0
1            0             0             0         0.0
2            0             0             0         0.0
3            0             0             0         0.0
4            0             0             0         0.0